# instructions
kinit --forwardable ruliu@NADA.KTH.SE
salloc --nodes=1 -t 00:05:00 -A edu20.DD2360

module load cuda/10.0
nvcc -arch=sm_30 kernel.cu -o akernel
srun -n 1 akernel

bash-4.2$ srun -n 1 akernel
# output is:

# Hello world from thread 0
# Hello world from thread 1
# Hello world from thread 2
# Hello world from thread 3
# Hello world from thread 4
# Hello world from thread 5
# Hello world from thread 6
# Hello world from thread 7
# Hello world from thread 8
# Hello world from thread 9
# Hello world from thread 10
# Hello world from thread 11
# Hello world from thread 12
# Hello world from thread 13
# Hello world from thread 14
# Hello world from thread 15
# Hello world from thread 16
# Hello world from thread 17
# Hello world from thread 18
# Hello world from thread 19
# Hello world from thread 20
# Hello world from thread 21
# Hello world from thread 22
# Hello world from thread 23
# Hello world from thread 24
# Hello world from thread 25
# Hello world from thread 26
# Hello world from thread 27
# Hello world from thread 28
# Hello world from thread 29
# Hello world from thread 30
# Hello world from thread 31
# Hello world from thread 128
# Hello world from thread 129
# Hello world from thread 130
# Hello world from thread 131
# Hello world from thread 132
# Hello world from thread 133
# Hello world from thread 134
# Hello world from thread 135
# Hello world from thread 136
# Hello world from thread 137
# Hello world from thread 138
# Hello world from thread 139
# Hello world from thread 140
# Hello world from thread 141
# Hello world from thread 142
# Hello world from thread 143
# Hello world from thread 144
# Hello world from thread 145
# Hello world from thread 146
# Hello world from thread 147
# Hello world from thread 148
# Hello world from thread 149
# Hello world from thread 150
# Hello world from thread 151
# Hello world from thread 152
# Hello world from thread 153
# Hello world from thread 154
# Hello world from thread 155
# Hello world from thread 156
# Hello world from thread 157
# Hello world from thread 158
# Hello world from thread 159
# Hello world from thread 32
# Hello world from thread 33
# Hello world from thread 34
# Hello world from thread 35
# Hello world from thread 36
# Hello world from thread 37
# Hello world from thread 38
# Hello world from thread 39
# Hello world from thread 40
# Hello world from thread 41
# Hello world from thread 42
# Hello world from thread 43
# Hello world from thread 44
# Hello world from thread 45
# Hello world from thread 46
# Hello world from thread 47
# Hello world from thread 48
# Hello world from thread 49
# Hello world from thread 50
# Hello world from thread 51
# Hello world from thread 52
# Hello world from thread 53
# Hello world from thread 54
# Hello world from thread 55
# Hello world from thread 56
# Hello world from thread 57
# Hello world from thread 58
# Hello world from thread 59
# Hello world from thread 60
# Hello world from thread 61
# Hello world from thread 62
# Hello world from thread 63
# Hello world from thread 192
# Hello world from thread 193
# Hello world from thread 194
# Hello world from thread 195
# Hello world from thread 196
# Hello world from thread 197
# Hello world from thread 198
# Hello world from thread 199
# Hello world from thread 200
# Hello world from thread 201
# Hello world from thread 202
# Hello world from thread 203
# Hello world from thread 204
# Hello world from thread 205
# Hello world from thread 206
# Hello world from thread 207
# Hello world from thread 208
# Hello world from thread 209
# Hello world from thread 210
# Hello world from thread 211
# Hello world from thread 212
# Hello world from thread 213
# Hello world from thread 214
# Hello world from thread 215
# Hello world from thread 216
# Hello world from thread 217
# Hello world from thread 218
# Hello world from thread 219
# Hello world from thread 220
# Hello world from thread 221
# Hello world from thread 222
# Hello world from thread 223
# Hello world from thread 224
# Hello world from thread 225
# Hello world from thread 226
# Hello world from thread 227
# Hello world from thread 228
# Hello world from thread 229
# Hello world from thread 230
# Hello world from thread 231
# Hello world from thread 232
# Hello world from thread 233
# Hello world from thread 234
# Hello world from thread 235
# Hello world from thread 236
# Hello world from thread 237
# Hello world from thread 238
# Hello world from thread 239
# Hello world from thread 240
# Hello world from thread 241
# Hello world from thread 242
# Hello world from thread 243
# Hello world from thread 244
# Hello world from thread 245
# Hello world from thread 246
# Hello world from thread 247
# Hello world from thread 248
# Hello world from thread 249
# Hello world from thread 250
# Hello world from thread 251
# Hello world from thread 252
# Hello world from thread 253
# Hello world from thread 254
# Hello world from thread 255
# Hello world from thread 64
# Hello world from thread 65
# Hello world from thread 66
# Hello world from thread 67
# Hello world from thread 68
# Hello world from thread 69
# Hello world from thread 70
# Hello world from thread 71
# Hello world from thread 72
# Hello world from thread 73
# Hello world from thread 74
# Hello world from thread 75
# Hello world from thread 76
# Hello world from thread 77
# Hello world from thread 78
# Hello world from thread 79
# Hello world from thread 80
# Hello world from thread 81
# Hello world from thread 82
# Hello world from thread 83
# Hello world from thread 84
# Hello world from thread 85
# Hello world from thread 86
# Hello world from thread 87
# Hello world from thread 88
# Hello world from thread 89
# Hello world from thread 90
# Hello world from thread 91
# Hello world from thread 92
# Hello world from thread 93
# Hello world from thread 94
# Hello world from thread 95
# Hello world from thread 160
# Hello world from thread 161
# Hello world from thread 162
# Hello world from thread 163
# Hello world from thread 164
# Hello world from thread 165
# Hello world from thread 166
# Hello world from thread 167
# Hello world from thread 168
# Hello world from thread 169
# Hello world from thread 170
# Hello world from thread 171
# Hello world from thread 172
# Hello world from thread 173
# Hello world from thread 174
# Hello world from thread 175
# Hello world from thread 176
# Hello world from thread 177
# Hello world from thread 178
# Hello world from thread 179
# Hello world from thread 180
# Hello world from thread 181
# Hello world from thread 182
# Hello world from thread 183
# Hello world from thread 184
# Hello world from thread 185
# Hello world from thread 186
# Hello world from thread 187
# Hello world from thread 188
# Hello world from thread 189
# Hello world from thread 190
# Hello world from thread 191
# Hello world from thread 96
# Hello world from thread 97
# Hello world from thread 98
# Hello world from thread 99
# Hello world from thread 100
# Hello world from thread 101
# Hello world from thread 102
# Hello world from thread 103
# Hello world from thread 104
# Hello world from thread 105
# Hello world from thread 106
# Hello world from thread 107
# Hello world from thread 108
# Hello world from thread 109
# Hello world from thread 110
# Hello world from thread 111
# Hello world from thread 112
# Hello world from thread 113
# Hello world from thread 114
# Hello world from thread 115
# Hello world from thread 116
# Hello world from thread 117
# Hello world from thread 118
# Hello world from thread 119
# Hello world from thread 120
# Hello world from thread 121
# Hello world from thread 122
# Hello world from thread 123
# Hello world from thread 124
# Hello world from thread 125
# Hello world from thread 126
# Hello world from thread 127
